version: '3.8'

services:
  api-monitor:
    build: .
    container_name: kiosk-api-monitor
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - API_BASE_URL=https://staging.orderwithinfi.com/kiosk-shopping-api
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    networks:
      - api-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: kiosk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api-network

  nginx:
    image: nginx:alpine
    container_name: kiosk-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./reports:/usr/share/nginx/html
    networks:
      - api-network
    depends_on:
      - api-monitor

networks:
  api-network:
    driver: bridge

volumes:
  reports:
  logs: 